### ISSUE TITLE
report error when running sample

### ISSUE THREAD

**Issue by somanybut** [openresty/stapxx#12]
when I run "./samples/ngx-rps.sxx -x 21148" on centos 6.4, it reports: Checking "/lib/modules/2.6.32-358.el6.x86_64/build/.config" failed with error: No such file or directory.

how I can resolve this problem.

**Comment by agentzh** [comment]
@somanybut Seems like you have not installed the kernel-deval package for your kernel. See the following systemtap installation document for more details:

https://www.sourceware.org/systemtap/SystemTap_Beginners_Guide/using-systemtap.html#install-kinfo

**Comment by somanybut** [comment]
thx. After I have installed the kernel_devel and the debug info packages. The sample runs normally.

**Comment by agentzh** [comment]
@somanybut Glad to hear that. I'm closing this.
