### ISSUE TITLE
Found 0 JITted samples.

### ISSUE THREAD

**Issue by rcritt** [openresty/stapxx#13]
Hello,

I have systemtap running on a RedHat 4.8.2-16 distribution.  

When I run the lj-lua-stacks.sxx script I am consistently getting "Found 0 JITted samples." as the result.  

I start systemtap, then go to a browser-page that runs lua code, then Control-c after that.  

Here is a sample I got recently.
> [root@ip-10-0-133-165 stapxx]# ./samples/lj-lua-stacks.sxx --skip-badvars -x 45739 > a.bt
> Found exact match for libluajit: /usr/local/openresty/luajit/lib/libluajit-5.1.so.2.1.0
> 
> WARNING: Start tracing 45739 (/usr/local/openresty/nginx/sbin/nginx)
> WARNING: Hit Ctrl-C to end.
> ^CWARNING: Found 0 JITted samples.

Is there something additional I should do to get data?  

Many thanks for providing these scripts btw,

Rollin

**Comment by agentzh** [comment]
@rcritt This tool is using the sampling approach which makes it suitable to run in a busy online system without much overhead. To get meaningful result, you need to *load* your nginx servers with tools like `ab` and `weighttp`. The higher CPU usage of that nginx worker process, the better results you will get :)

**Comment by rcritt** [comment]
Hi AgentZH,

I am using wrk to try to get some traffic going.  We are doing 3 threads, 100 connections per thread, for 30 seconds.  We are transferring about 10MB/sec in that test.

The Systemtap we are using is installed from yum...  Have people had issues with that sort of configuration?

**Comment by rcritt** [comment]
I just tried this with a hand-built version of Systemtap, that was put in-front at the path etc to precede the RPM/YUM package.

It is still returning 0 JITted samples.

**Comment by rcritt** [comment]
I just ran ngx-rps and am gettting 0 req/sec when running the wrk load-test (3 threads, 100 connections).
=======
./samples/ngx-rps.sxx -x 9737
WARNING: Tracing process 9737 (/usr/local/openresty/nginx/sbin/nginx).
Hit Ctrl-C to end.
[1426170613] 0 req/sec
[1426170614] 0 req/sec
[1426170615] 0 req/sec
=======

I also see no data for ngx-req-latency-distr.
=======
./samples/ngx-req-latency-distr.sxx -x 9737
Start tracing process 9737 (/usr/local/openresty/nginx/sbin/nginx)...
Hit Ctrl-C to end.
^C
No samples found so far.
=======

**Comment by agentzh** [comment]
@rcritt Are you 100% sure the CPU usage of that worker process being traced (with pid 9737) is high enough? Please note that you should not trace the master or cache processes because these processes do not serve any requests. Only trace the busiest nginx worker process (to simplify the test, you can start with only one single worker in nginx.conf by configuring `worker_processes 1;`).

**Comment by rcritt** [comment]
That did the trick!  1 worker and going to that process got me a bunch of JITted stuff.  Thank you!
