### ISSUE TITLE
Detect memory leak in a high-volume system

### ISSUE THREAD

**Issue by qqibrow** [openresty/stapxx#14]
Hi, Yichun

I am using your sample-bt-leak to detect memory leak in a high volume system and both my program and stap programs crashed. The stap program first showed:

ERROR: Array overflow, check MAXMAPENTRIES near identifier 'ptr2bt' at <input>:63:17

Then I increaseed MAXMAPENTRIES to be 100000 and then I got error:

ERROR: probe overhead exceeded threshold

I think the problem is so many entries are been added into the map ptr2bt and cause it overflow. Do u have any idea how to avoid such problem? Thank you!

**Comment by agentzh** [comment]
@qqibrow I think you should specify the `-D STP_NO_OVERLOAD` option.

**Comment by chenshanyi** [comment]
After modifying MAXMAPENTRIES, MAXSTRINGLEN, why is there a significant increase in memory?
