### ISSUE TITLE
lj-lua-stacks.sxx: semantic error: type definition 'lua_State' not found

### ISSUE THREAD

**Issue by rkearsley** [openresty/stapxx#17]
Hi
First time trying stapxx tools, but get this error:

    ~/stapxx# ./samples/lj-lua-stacks.sxx --skip-badvars -x 14851 > a.bt
    Found exact match for libluajit: /usr/local/lib/libluajit-5.1.so.2.1.0
    WARNING: cannot find module /usr/local/lib/libluajit-5.1.so.2.1.0 debuginfo: No DWARF information      found [man warning::debuginfo]
    semantic error: type definition 'lua_State' not found in '/usr/local/lib/libluajit-5.1.so.2.1.0': operator '@cast' at stapxx-OIz7lBDX/luajit.stp:162:12
        source:     return @cast(L, "lua_State", "/usr/local/lib/libluajit-5.1.so.2.1.0")->glref->ptr32
                           ^

    Pass 2: analysis failed.  [man error::pass2]

Kernel: 3.16.0-30-generic #40~14.04.1-Ubuntu

nginx: nginx version: nginx/1.9.1
built by gcc 4.8.2 (Ubuntu 4.8.2-19ubuntu1)
built with OpenSSL 1.0.1f 6 Jan 2014
TLS SNI support enabled
configure arguments: --with-debug --with-ipv6 --with-http_ssl_module --with-http_spdy_module --with-http_stub_status_module --with-file-aio --with-threads --with-http_flv_module --with-http_mp4_module --with-http_geoip_module --with-http_gzip_static_module --add-module=../lua-nginx-module-master --add-module=../nginx-rtmp-module-1.1.7

stap:  stap -V
Systemtap translator/driver (version 2.3/0.158, Debian version 2.3-1ubuntu1 (trusty))
Copyright (C) 2005-2013 Red Hat, Inc. and others
This is free software; see the source for copying conditions.
enabled features: AVAHI LIBSQLITE3 NSS TR1_UNORDERED_MAP NLS

Any help much appreciated!
Thanks
Richard

**Comment by agentzh** [comment]
@rkearsley The error message already explains the cause: your LuaJIT build lacks debug symbols. Please note that, LuaJIT builds omit debug symbols by default, to enable it, you need to build LuaJIT like this:

```
make CCDEBUG=-g
```

BTW, you're recommended to use the OpenResty bundle which enables debug symbols in its LuaJIT build by default.

**Comment by rkearsley** [comment]
Hi
Thanks, that got my past the first message, but I'm still left with the compilation failed

    stapxx# ./samples/lj-lua-stacks.sxx --skip-badvars -x 30166 > a.bt
    Found exact match for libluajit: /usr/local/lib/libluajit-5.1.so.2.1.0
    In file included from /usr/share/systemtap/runtime/linux/task_finder.c:17:0,
                 from /usr/share/systemtap/runtime/linux/runtime.h:188,
                 from /usr/share/systemtap/runtime/runtime.h:24,
                 from /tmp/stapyKF7gK/stap_883f26242f00a92ebecfc45239e19a57_38296_src.c:25:
    /usr/share/systemtap/runtime/linux/task_finder2.c: In function ‘__stp_utrace_attach_match_filename’:
    /usr/share/systemtap/runtime/linux/task_finder2.c:821:11: error: incompatible types when assigning to type ‘uid_t’ from type ‘kuid_t’
      tsk_euid = task_euid(tsk);
           ^
    /usr/share/systemtap/runtime/linux/task_finder2.c: In function ‘stap_start_task_finder’:
    /usr/share/systemtap/runtime/linux/task_finder2.c:1711:12: error: incompatible types when assigning to type ‘uid_t’ from type ‘kuid_t’
       tsk_euid = task_euid(tsk);
            ^
    In file included from /usr/share/systemtap/runtime/linux/runtime.h:194:0,
                 from /usr/share/systemtap/runtime/runtime.h:24,
                 from /tmp/stapyKF7gK/stap_883f26242f00a92ebecfc45239e19a57_38296_src.c:25:
    /usr/share/systemtap/runtime/sym.c: In function ‘_stp_snprint_addr’:
    /usr/share/systemtap/runtime/sym.c:567:4: error: implicit declaration of function         ‘preempt_enable_no_resched’ [-Werror=implicit-function-declaration]
    preempt_enable_no_resched();
    ^
    In file included from include/linux/sched.h:55:0,
                 from include/linux/ptrace.h:5,
                 from include/linux/ftrace.h:13,
                 from include/linux/kprobes.h:42,
                 from /usr/share/systemtap/runtime/linux/runtime.h:21,
                 from /usr/share/systemtap/runtime/runtime.h:24,
                 from /tmp/stapyKF7gK/stap_883f26242f00a92ebecfc45239e19a57_38296_src.c:25:
    /usr/share/systemtap/runtime/transport/control.c: In function ‘_stp_ctl_write_cmd’:
    include/linux/cred.h:333:25: error: incompatible types when initializing type ‘uid_t’ using type ‘kuid_t’
     #define current_euid()  (current_cred_xxx(euid))
                         ^
    /usr/share/systemtap/runtime/transport/control.c:41:15: note: in expansion of macro ‘current_euid’
      uid_t euid = current_euid();
               ^
    In file included from /usr/share/systemtap/runtime/linux/print.c:17:0,
                 from /usr/share/systemtap/runtime/print.c:17,
                 from /usr/share/systemtap/runtime/runtime_context.h:22,
                 from /tmp/stapyKF7gK/stap_883f26242f00a92ebecfc45239e19a57_38296_src.c:933:
    /usr/share/systemtap/runtime/transport/transport.c: In function ‘_stp_transport_init’:
    /usr/share/systemtap/runtime/transport/transport.c:344:11: error: incompatible types when assigning to type ‘uid_t’ from type ‘kuid_t’
      _stp_uid = current_uid();
           ^
    /usr/share/systemtap/runtime/transport/transport.c:345:11: error: incompatible types when assigning to type ‘gid_t’ from type ‘kgid_t’
      _stp_gid = current_gid();
           ^
    cc1: all warnings being treated as errors
    make[1]: *** [/tmp/stapyKF7gK/stap_883f26242f00a92ebecfc45239e19a57_38296_src.o] Error 1
    make: *** [_module_/tmp/stapyKF7gK] Error 2
    WARNING: kbuild exited with status: 2
    Pass 4: compilation failed.  [man error::pass4]
    Tip: /usr/share/doc/systemtap/README.Debian should help you get started.


Many thanks
Richard

**Comment by rkearsley** [comment]
solved with compiling systemtap 2.6: http://openresty.org/#BuildSystemtap

Thanks!
