### ISSUE TITLE
lj-lua-bt.sxx locate infinite loop in lua code issue

### ISSUE THREAD

**Issue by redcloser** [openresty/stapxx#26]
luajit version: 2.1.0

i write an infinite loop in Lua code like this :

while (1) do
end

then use lj-lua-bt.sxx --skip-badvars -x ${pid} to locate this infinite loop ,

 /home/game/flameGraph/stapxx-master/samples/lj-lua-bt.sxx --skip-badvars -x 35193
Found exact match for libluajit: /usr/local/openresty/luajit/lib/libluajit-5.1.so.2.1.0
Start tracing 35193 (/usr/local/openresty/nginx/sbin/nginx)

then hang and keep waiting here, can not locate the infinite loop in lua code.

**Comment by agentzh** [comment]
@redcloser Try this tool instead: https://github.com/openresty/stapxx#lj-lua-stacks

BTW, are you really gonna write that silly empty infinite loop in the real world? Infinite Lua loops in real OpenResty/Lua systems tend to be much bigger and even subtle :)

**Comment by redcloser** [comment]
@agentzh 
this empty infinite loop is used to test those stapxx tools can locate this infinite loop or not.
and i try this tool stapxx#lj-lua-stacks, terminal displays as follows

+ /home/game/flameGraph/stapxx-master/samples/lj-lua-stacks.sxx --arg time=5 --skip-badvars -x 35194
Found exact match for libluajit: /usr/local/openresty/luajit/lib/libluajit-5.1.so.2.1.0
WARNING: Start tracing 35194 (/usr/local/openresty/nginx/sbin/nginx)
WARNING: Please wait for 5 seconds...
WARNING: Time's up. Quitting now...
WARNING: Found 0 JITted samples.

still can't locate the infinite loop lua code

**Comment by agentzh** [comment]
@redcloser Systemtap based tools need entry points (usually C function calls) for the probes. Such empty loop is compiled down to a few bare CPU instructions which provide nothing for the stap tools to probe on. In such case, you should try the `lbt` gdb command provided by the `openresty-gdb-utils` repository instead:

https://github.com/openresty/openresty-gdb-utils#lbt

I've tested your example on my side and the gdb tool works as expected:

```console
$ cat a.lua
function main()
    while true do
    end
end
main()

$ gdb --args luajit a.lua
GNU gdb (GDB) Fedora 7.10.1-31.fc23
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from luajit...done.
(gdb) r
Starting program: /opt/luajit21/bin/luajit a.lua
^C
Program received signal SIGINT, Interrupt.
0x000000000bcbfff0 in ?? ()
(gdb) lbt
@a.lua:2
@a.lua:5
C:pmain
```

**Comment by agentzh** [comment]
@redcloser As I've said, hot loops in real world Lua applications can seldom or never be this empty and naive.

**Comment by agentzh** [comment]
@redcloser Sorry, I take back my previous comment on the lack of probing points in an empty Lua loop. Actually the tool `lj-lua-bt` and `lj-lua-stacks` use the perf tracepoints for the probes, so it doesn't matter. I just tried the `lj-lua-bt` tool on my side against the `a.lua` example file given agove and it works.

First of all, keep the infinite loop script running:

```console
$ luajit a.lua
```

Then in another console window, run the stap tool `lj-lua-bt`:

```console
$ pgrep luajit
85201

$ lj-lua-bt.sxx -x 85201
/home/agentzh/git/stapxx/tapset/luajit.sxx: line 7: libluajit is not found, assuming it is statically linked.
Start tracing 85201 (/opt/luajit21/bin/luajit-2.1.0-beta2)
@a.lua:2
@a.lua:5
C:pmain
```

We are getting the exactly same output as the `lbt` gdb command in an earlier comment.

I've also tested the `lj-lua-stacks` tools and it works too:

```console
$ lj-lua-stacks.sxx -x 85201 --arg time=1
/home/agentzh/git/stapxx/tapset/luajit.sxx: line 7: libluajit is not found, assuming it is statically linked.
WARNING: Start tracing 85201 (/opt/luajit21/bin/luajit-2.1.0-beta2)
WARNING: Please wait for 1 seconds...
WARNING: Time's up. Quitting now...
0xbcbfff0
T:@a.lua:1
@a.lua:1
@a.lua:0
C:pmain
	992
WARNING: Found 992 JITted samples.
```

Maybe there is a problem in your systemtap installation, Linux kernel, and/or your LuaJIT installation?

Some info about my system:

```console
$ uname -a
Linux fedora64 4.8.13-100.fc23.x86_64 #1 SMP Fri Dec 9 14:51:40 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ stap -V
Systemtap translator/driver (version 3.1/0.161, commit release-3.0-303-g9ed478545124 + changes)
Copyright (C) 2005-2016 Red Hat, Inc. and others
This is free software; see the source for copying conditions.
tested kernel versions: 2.6.18 ... 4.9-rc1
enabled features: BOOST_STRING_REF LIBSQLITE3 LIBXML2 NLS READLINE

$ luajit -v
LuaJIT 2.1.0-beta2 -- Copyright (C) 2005-2016 Mike Pall. http://luajit.org/
```

I'm also using the git master versions of those stap++ tools.

**Comment by agentzh** [comment]
@redcloser It's worth mentioning that unlike `lj-lua-bt` and `lbt`, the `lj-lua-stacks` tool outputs the line number of the beginning of the containing Lua function definition, hence the slightly different output seen above.

**Comment by redcloser** [comment]
@agentzh TKS 

function main()
    while true do
    end
end
main()

i try this code like this /usr/local/openresty/luajit/bin/luajit-2.1.0-alpha a.lua
and use 
+ /home/game/flameGraph/stapxx-master/samples/lj-lua-stacks.sxx --arg time=5 --skip-badvars -x 42934
/home/game/flameGraph/stapxx-master/tapset/luajit.sxx: line 7: libluajit is not found, assuming it is statically linked.
WARNING: Start tracing 42934 (/usr/local/openresty/luajit/bin/luajit-2.1.0-alpha)
WARNING: Please wait for 5 seconds...
WARNING: Time's up. Quitting now...
0xbcafff0
T:@a.lua:2
@a.lua:2
@a.lua:0
C:pmain

it  works
 
but i run this code use
    location /loop {
        content_by_lua_file /home/game/lua-server/a.lua;
    } 
and request this url and try this tool output like below
+ /home/game/flameGraph/stapxx-master/samples/lj-lua-stacks.sxx --arg time=5 --skip-badvars -x 43935
Found exact match for libluajit: /usr/local/openresty/luajit/lib/libluajit-5.1.so.2.1.0
WARNING: Start tracing 43935 (/usr/local/openresty/nginx/sbin/nginx)
WARNING: Please wait for 5 seconds...
WARNING: Time's up. Quitting now...
WARNING: Found 0 JITted samples.

i've no idea why

**Comment by agentzh** [comment]
Are you 100% sure you are tracing the right nginx worker process?

**Comment by redcloser** [comment]
PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                                                                                                                       
44315 www-data  20   0 1257m  18m 3188 R  100  0.2 125:56.66 nginx: worker process                                                                                                                                                          
 

+ /home/game/flameGraph/stapxx-master/samples/lj-lua-stacks.sxx --arg time=5 --skip-badvars -x 44315
Found exact match for libluajit: /usr/local/openresty/luajit/lib/libluajit-5.1.so.2.1.0
WARNING: Start tracing 44315 (/usr/local/openresty/nginx/sbin/nginx)
WARNING: Please wait for 5 seconds...
WARNING: Time's up. Quitting now...
WARNING: Found 0 JITted samples.

**Comment by redcloser** [comment]
and this is my nginx version 
nginx version: openresty/1.7.7.2
built by gcc 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) 
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-I/home/mzhou/ngx_openresty-1.7.7.2/build/luajit-root/usr/local/openresty/luajit/include/luajit-2.1 -O2' --add-module=../ngx_devel_kit-0.2.19 --add-module=../echo-nginx-module-0.57 --add-module=../xss-nginx-module-0.04 --add-module=../ngx_coolkit-0.2rc2 --add-module=../set-misc-nginx-module-0.28 --add-module=../form-input-nginx-module-0.10 --add-module=../encrypted-session-nginx-module-0.03 --add-module=../srcache-nginx-module-0.28 --add-module=../ngx_lua-0.9.14 --add-module=../ngx_lua_upstream-0.02 --add-module=../headers-more-nginx-module-0.25 --add-module=../array-var-nginx-module-0.03 --add-module=../memc-nginx-module-0.15 --add-module=../redis2-nginx-module-0.11 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.13 --add-module=../rds-csv-nginx-module-0.05 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -L/home/mzhou/ngx_openresty-1.7.7.2/build/luajit-root/usr/local/openresty/luajit/lib' --with-http_ssl_module

**Comment by redcloser** [comment]
sorry my nginx configure without with-debug
i recompile nginx with-debug 
and one more try 

+ /home/game/flameGraph/stapxx-master/samples/lj-lua-stacks.sxx --arg time=5 --skip-badvars -x 57390
/home/game/flameGraph/stapxx-master/tapset/luajit.sxx: line 7: libluajit is not found, assuming it is statically linked.
semantic error: unresolved struct lua_State: operator '->' at stapxx-tnv77KCO/luajit.stp:162:74
        source:     return @cast(L, "lua_State", "/usr/local/openresty/nginx/sbin/nginx")->glref->ptr32
                                                                                         ^

Pass 2: analysis failed.  [man error::pass2]

**Comment by agentzh** [comment]
@redcloser Noted some problems in your setup:

1. Your OpenResty is very old, the latest version is 1.11.2.2. Better upgrade to the latest version. See https://openresty.org/en/download.html
2. You should use OpenResty's own LuaJIT instead of your version, which apparently lacks debuginfo.
3. It's not required to pass `--with-debug` to `./configure` while building OpenResty for these systemtap or gdb tools.

**Comment by agentzh** [comment]
@redcloser I've just tried the empty Lua infinite loop example on my side in OpenResty:

```nginx
location = /t {
    content_by_lua_block {
        function main()
            while true do
            end
        end
        main()
    }
}
```

And the `lj-lua-bt.sxx` tool works as expected on my side:

```console
$ lj-lua-bt.sxx -x 127540
Found exact match for libluajit: /opt/luajit21dbg/lib/libluajit-5.1.so.2.1.0
Start tracing 127540 (/home/agentzh/git/lua-nginx-module/work/nginx/sbin/nginx)
=content_by_lua(nginx.conf:46):4
=content_by_lua(nginx.conf:46):6
```

And also the `lj-lua-stacks.sxx` tool:

```console
$ lj-lua-stacks.sxx -x 127540 --arg time=1
Found exact match for libluajit: /opt/luajit21dbg/lib/libluajit-5.1.so.2.1.0
WARNING: Start tracing 127540 (/home/agentzh/git/lua-nginx-module/work/nginx/sbin/nginx)
WARNING: Please wait for 1 seconds...
WARNING: Time's up. Quitting now...
0x7f77f9f0fff0
T:=content_by_lua(nginx.conf:46):2
=content_by_lua(nginx.conf:46):2
=content_by_lua(nginx.conf:46):1
	992
WARNING: Found 992 JITted samples.
```

I'm (mostly) using the latest OpenResty 1.11.2.2 with the default build options.

**Comment by redcloser** [comment]
/home/game/flameGraph/stapxx-master/samples/lj-lua-stacks.sxx --arg time=5 --skip-badvars -x 57390
/home/game/flameGraph/stapxx-master/tapset/luajit.sxx: line 7: libluajit is not found, assuming it is statically linked.
semantic error: unresolved struct lua_State: operator '->' at stapxx-tnv77KCO/luajit.stp:162:74
source: return @cast(L, "lua_State", "/usr/local/openresty/nginx/sbin/nginx")->glref->ptr32

i find one issue like this error log https://github.com/openresty/stapxx/issues/17
and my log did not show that luajit lacks debuginfo.

for this problem “You should use OpenResty's own LuaJIT instead of your version, which apparently lacks debuginfo.” maybe not correct

**Comment by redcloser** [comment]
and can you show me your nginx -V, i wane use it to check my probleams? thank you very much

**Comment by agentzh** [comment]
@redcloser Try the latest OpenResty release with no `./configure` options. I don't want to waste more time on this. Alas.

**Comment by redcloser** [comment]
ok thank you very much，i'am trying the laset openresty release now。 everything is work correct

**Comment by agentzh** [comment]
Cool!
