### ISSUE TITLE
ERROR: module version mismatch

### ISSUE THREAD

**Issue by dingdongnigetou** [openresty/stapxx#28]
system: Centos7
kernel: 3.10.0-229.el7.x86_64
shell command: stap -v -e 'probe vfs.read {printf("read performed\n"); exit()}'
**error comes out:** 
`Pass 1: parsed user script and 465 library scripts using 212868virt/44160res/2824shr/41600data kb, in 140usr/0sys/152real ms.
Pass 2: analyzed script: 1 probe, 1 function, 7 embeds, 0 globals using 334808virt/167324res/4092shr/163540data kb, in 850usr/180sys/1024real ms.
Pass 3: using cached /root/.systemtap/cache/91/stap_910821b500037ab6493098235f73ae89_2677.c
Pass 4: using cached /root/.systemtap/cache/91/stap_910821b500037ab6493098235f73ae89_2677.ko
Pass 5: starting run.
ERROR: module version mismatch (#1 SMP Mon Mar 9 16:14:50 CDT 2015 vs #1 SMP Fri Mar 6 11:36:42 UTC 2015), release 3.10.0-229.el7.x86_64
WARNING: /opt/stap/bin/staprun exited with status: 1
Pass 5: run completed in 0usr/10sys/44real ms.
Pass 5: run failed.  [man error::pass5]`

install step:
* kernel-debuginfo-3.10.0-229.el7.x86_64.rpm
* kernel-debuginfo-common-x86_64-3.10.0-229.el7.x86_64.rpm
* kernel-devel-3.10.0-229.el7.x86_64.rpm
* yum install systemtap

**Comment by agentzh** [comment]
@dingdongnigetou Seems like you need to wipe out any cached stap kernel modules.

**Comment by agentzh** [comment]
This is really a systemtap question.

**Comment by dingdongnigetou** [comment]
ok, my mistake, thank you：）

**Comment by dingdongnigetou** [comment]
hi agentzh, i do wipe out the cached, by this: `rm -rf ~/.systemtap/cache/`
but it seams not work, the same error, could you help me?

**Comment by agentzh** [comment]
@dingdongnigetou Try building systemtap from the latest source, as in

https://openresty.org/en/build-systemtap.html

**Comment by dingdongnigetou** [comment]
wao, i tried to modify the UTS_VERSION in /usr/src/kernels/3.10.0-229.el7.x86_64/include/generated/compile.h, and then rebuild the systemtap from source, and it works!

**Comment by dingdongnigetou** [comment]
the same with `uname -v`
