### ISSUE TITLE
centos 7 libc-2.17.so debuginfo: No DWARF information found

### ISSUE THREAD

**Issue by loveghost** [openresty/stapxx#30]
嗨，春哥，我用sample-bt-leaks.sxx 检查内存泄漏问题。火焰图环境我已经安装好，
[root@bogon stapxx]# uname -a
Linux bogon 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
执行遇到如下错误：
[root@bogon stapxx]# ./samples/sample-bt-leaks.sxx  -x 4448 --arg time=5 -D STP_NO_OVERLOAD -D MAXMAPENTRIES=10000 > a.bt
Found exact match for libc: /usr/lib64/libc-2.17.so
WARNING: cannot find module /usr/lib64/libc-2.17.so debuginfo: No DWARF information found [man warning::debuginfo]
semantic error: while processing probe process("/usr/lib64/libc-2.17.so").function("malloc").return from: process("/usr/lib64/libc-2.17.so").function("malloc").return

semantic error: type definition 'size_t' not found in '/usr/lib64/libc-2.17.so': operator '@cast' at <input>:58:28
        source:                 p = ptr - &@cast(0, "size_t")[1]
                                           ^

Missing separate debuginfos, use: debuginfo-install glibc-2.17-157.el7_3.1.x86_64
Pass 2: analysis failed.  [man error::pass2]
Number of similar warning messages suppressed: 35.
Rerun with -v to see them.

**Comment by agentzh** [comment]
Please, do not use Chinese here. This place is considered English only. If you
really want to use Chinese, please join and post to the openresty (Chinese)
mailing list instead. Please see https://openresty.org/en/community.html Thanks for
your cooperation.

Regarding your question, you error message already told you what to do but unfortunately you were not paying attention. To quote:

> Missing separate debuginfos, use: debuginfo-install glibc-2.17-157.el7_3.1.x86_64

**Comment by loveghost** [comment]
thank you

**Comment by z00402049** [comment]
semantic error: type definition 'size_t' not found in '/usr/lib64/libc-2.17.so': operator '@cast' at <input>:58:28
        source:                 p = ptr - &@cast(0, "size_t")[1]
                                           ^

Pass 2: analyzed script: 7 probe(s), 13 function(s), 7 embed(s), 7 global(s) using 227596virt/43748res/5840shr/38168data kb, in 30usr/130sys/222real ms.
Pass 2: analysis failed.  [man error::pass2]

我也遇到这个问题，已经使用debuginfo-install glibc-2.17-111.h29.x86_64进行安装glibc，但是仍然报这个错误，也没有发现中文的地方，这个要如何解决呢？
