### ISSUE TITLE
perl env question

### ISSUE THREAD

**Issue by tweyseo** [openresty/stapxx#38]
[root@localhost stapxx]# ./stap++ 
: No such file or directory
[root@localhost stapxx]# perl stap++ 
No input file specified.
[root@localhost stapxx]# ./test 
hello world!

content in test:
#!/usr/bin/env perl
printf("hello world!\n")

why?

**Comment by spacewander** [comment]
Run `strace -f ./stap++` to see what happened?

**Comment by tweyseo** [comment]
i was not familiar with 'strace', and this is the result:
execve("./stap++", ["./stap++"], [/* 26 vars */]) = 0
brk(0)                                  = 0x2381000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f350aae4000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY)      = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=81712, ...}) = 0
mmap(NULL, 81712, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f350aad0000
close(3)                                = 0
open("/lib64/libc.so.6", O_RDONLY)      = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0000\356\341\375=\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1926800, ...}) = 0
mmap(0x3dfde00000, 3750152, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x3dfde00000
mprotect(0x3dfdf8b000, 2093056, PROT_NONE) = 0
mmap(0x3dfe18a000, 20480, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x18a000) = 0x3dfe18a000
mmap(0x3dfe18f000, 18696, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x3dfe18f000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f350aacf000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f350aace000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f350aacd000
arch_prctl(ARCH_SET_FS, 0x7f350aace700) = 0
mprotect(0x3dfe18a000, 16384, PROT_READ) = 0
mprotect(0x3dfd81f000, 4096, PROT_READ) = 0
munmap(0x7f350aad0000, 81712)           = 0
brk(0)                                  = 0x2381000
brk(0x23a2000)                          = 0x23a2000
open("/usr/lib/locale/locale-archive", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=99158576, ...}) = 0
mmap(NULL, 99158576, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f3504c3c000
close(3)                                = 0
execve("/usr/lib64/qt-3.3/bin/perl\r", ["perl\r", "./stap++"], [/* 26 vars */]) = -1 ENOENT (No such file or directory)
execve("/usr/local/sbin/perl\r", ["perl\r", "./stap++"], [/* 26 vars */]) = -1 ENOENT (No such file or directory)
execve("/usr/local/bin/perl\r", ["perl\r", "./stap++"], [/* 26 vars */]) = -1 ENOENT (No such file or directory)
execve("/sbin/perl\r", ["perl\r", "./stap++"], [/* 26 vars */]) = -1 ENOENT (No such file or directory)
execve("/bin/perl\r", ["perl\r", "./stap++"], [/* 26 vars */]) = -1 ENOENT (No such file or directory)
execve("/usr/sbin/perl\r", ["perl\r", "./stap++"], [/* 26 vars */]) = -1 ENOENT (No such file or directory)
execve("/usr/bin/perl\r", ["perl\r", "./stap++"], [/* 26 vars */]) = -1 ENOENT (No such file or directory)
execve("/root/bin/perl\r", ["perl\r", "./stap++"], [/* 26 vars */]) = -1 ENOENT (No such file or directory)
execve("/home/performance-analysis/systemtap/bin//perl\r", ["perl\r", "./stap++"], [/* 26 vars */]) = -1 ENOENT (No such file or directory)
write(2, "/usr/bin/env: ", 14/usr/bin/env: )          = 14
)                   = 5l
open("/usr/share/locale/locale.alias", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=2512, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f350aae3000
read(3, "# Locale name alias data base.\n#"..., 4096) = 2512
read(3, "", 4096)                       = 0
close(3)                                = 0
munmap(0x7f350aae3000, 4096)            = 0
open("/usr/share/locale/en_US.UTF-8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US.utf8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.UTF-8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.utf8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
write(2, ": No such file or directory", 27: No such file or directory) = 27
write(2, "\n", 1
)                       = 1
close(1)                                = 0
close(2)                                = 0
exit_group(127)                         = ?

**Comment by spacewander** [comment]
Looks like `perl` can't be found in your `$PATH`.
Run `strace -f` with other cases and compare their output?

**Comment by agentzh** [comment]
Apparently `/usr/bin/env` cannot find your `perl` in the PATH environment. Consider it resolved.
